{% set version = "2.1.1" %}

package:
  name: jsonfield
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jsonfield/jsonfield-{{ version }}.tar.gz
  sha256: ed7c5e1829e9453e24a8bebef1e702ffe402e6def6b326f0e0b88764c59a6dc7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip
  run:
    - python
    - django >=1.8.0

test:
  imports:
    - jsonfield

about:
  home: https://github.com/dmkoch/django-jsonfield/
  license: MIT
  license_file: LICENSE
  summary: 'A reusable Django field that allows you to store validated JSON in your model.'
  license_family: MIT

extra:
  recipe-maintainers:
    - ocefpaf
