{% set version = "3.0.0" %}

package:
  name: jsonfield
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jsonfield/jsonfield-{{ version }}.tar.gz
  sha256: 1a17efe9a26850e9175900cb37cf30c6182fc2251989f8af44ef47fbbf48eaff

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip
  run:
    - python
    - django >=1.11
    - six

test:
  imports:
    - jsonfield

about:
  home: https://github.com/dmkoch/django-jsonfield/
  license: MIT
  license_file: LICENSE
  summary: 'A reusable Django field that allows you to store validated JSON in your model.'
  license_family: MIT

extra:
  recipe-maintainers:
    - ocefpaf
