{% set version = "1.0.3" %}

package:
  name: jsonfield
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jsonfield/jsonfield-{{ version }}.tar.gz
  sha256: 7e7f73a675c518712badd783279e26d164140f3fc2ed7a32102c3d08a6a2a4a7

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - django >=1.8.0

test:
  imports:
    - jsonfield

about:
  home: https://github.com/dmkoch/django-jsonfield/
  license: MIT
  # license_file: LICENSE
  summary: 'A reusable Django field that allows you to store validated JSON in your model.'
  license_family: MIT

extra:
  recipe-maintainers:
    - ocefpaf
