travis:
  secure:
    BINSTAR_TOKEN: vnRiJqsmHW+xp9ZLw80nr9sOHy+XpZuvBUR3lI3XT3lgUHJh7gE1b34uj1brXnRkK17MPcA4hn6Liejs9bOxLq0PU7WNV0Pxz/eVMQVD4LlnaPn9dvbBE2kFz7syaKgbnPz67cLhB/tRrv1B4RruXNXa/ADa1qA0yksw21GAgM9GrgpBZ5/0toRbGNsHIW+Ag8mmG0wA2NLEzQLRk9y2VZsTnRAv2H/MWF9ColLHKKb71a2RYQYmOwZupsFIHq1LLCNO4Omv0kW1cDmifXTxoPDNlT8AWiu+5LZ22VF8zBeDQbDGR2BKHeGlv++JffZuzzvx41EeXFql/FIK3duvm7ue+dPNHB56BuU7o0V1T/HRdPGz582Bp0JXjsWS9xB24H5Q/1cXOWODQlIRpwqq8eelBMyPdEs382K6UYgDmEmTi3HgfYXTO1DNf1DJhLxUoZkDuLBVarehmq+w+cTGTAOFU7C7Nh+yTom+s5QG3Ny1a7jSpY6BfUA+Ye6U1cH1y71FF4Ok8ugjIu0jP3Momj4V79hRUfoH8/dDeOqs9T1Tekp0F7xjgu3GCgfju/jxPpyWxAJBbhNH6ICbBjlovNJ9B2/jEeN8lCkTPPC4SFjRJA8E5F5YZqucBb2GsZh544c9pmfdOLjG0/rfeLnIAnxbdmkt8G1pEVGiF5IGVvg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
