travis:
  secure:
    BINSTAR_TOKEN: Q/QHxW/c7g3LDNTAOn/CcuCfZBRbfOuFBXI3vxWCN/liEma/s06K+OnGw+pbjEHLAQ/+s4kDnCGXnQdIVmqxMbPgcIC0pKB91DIDlWb9lcMfqSEEA+bltDJ/arwW2rOjyDk4UcUKkucdsdM/+7RsMKqli4K9pdSYrq71T2C1wCl3FpJBrjQiR1rdynONdWxBAUYaZcFFEutzpi+4ck0cn+s087i75hbtXtFwoqy2FFl4x+LsnEYe9BZCzS3aq2/i/Z2iwRVDr/zO4xDAFls4dCFHK91LN3CkfvwIfSObRXFC9bn2B/e0WpugRbLAVJZyDps+JZZ7MDxWq1AGXyKQtskwjS6LAuLXofo6y3zu0p0+pYNCJjl7p3IIkz0bizfoZmcVv00H7GWLCiU3kSDcvhHx7UqOvIFAdEjyYiRHVDO6ngqmeFBID+esDB23Py8tQtzN1RLRQH/NjrndzXVFapWyZq7UGFSicrT54dfeU09hAhsJyfGb2BPvfZG08VYIsDmpZTmo+MQ6qyKIdXuPKnKTtsPIuES/piU3ynRu6+teEHSQotOw7qN3KtFsM2xeMLdM/p4bWjWRohkqKhDQYJdE6ZmJVpNAJ63ckxxP3pFhtYHa85Abq/o3xUxwcJXk1ZBYo04joBJHYtFXqoPhg2nnFxNBCoimVNctFTPlU54=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
